apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tools
  name: tools
spec:
  containers:
  - image: gonzaloacosta/tools
    name: tools
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
